language: python
python: '2.7'
install: true
script: true
deploy:
  provider: s3
  access_key_id: AKIAJQBVY4O4CWIYF7IQ
  bucket: thug-r.life
  skip_cleanup: true
  region: us-east-1
  local_dir: public
    secure: H4zOEeW/Zhy2XgXcElHPuEwlwvT07T+VSYfvjfprMb+hayv4AUz6V3a4NKOFfT+Z0RUi60BeqrasbbWqewmM4UUNeHIablmueO/lJOhRS7IRAaFTHMPD1uPjLXepuEr7lWrElUuCStJOouu+lKC4BF6w/fVmnq9G1M6VA8Zj8dhVLJ7EkAj23dk+HyH63zMQQYtRcFIBvRoEYy8HJ1rPmZ7XJF3mf68XLdpmSxAfpyLFvQgau1GGR1GV+GwAKPVYCSnrxiAaRgATbYAJM/oF3ATBCQfOucFRnjPz946ri/DxThgzDecfYBtdzN5BEny/cXVB7h1HUyhv5HCCN2r0Nt0buAat0uk4NlEndTHtOMNxA1KGzThOPLY4woME1VqtBYYPxQI5W5b2rXrXrOEX3egl8UE/nGv00ltjJWOGF3Brg6Gudy+QGVwt6LfbzkuAS8WsMIlENZ13Y1vcSc0epI+C2h0wP5tgjAgAOqFPT5MzwUQ/6wG5n6hZmF57KbMazNEz8I4tmByEf4bugzg4mAScHEb/FyPbY2xRT3v+fD0EjyyDCziBgWTMqQHicvX6Pts+1Rd+YOhhMCQN+22uujngUCcXxMB7ATr0kxmBo+Du8SA7BgKxo9c3YcrZRy7yrXP5ytfkbUKSrzoSy0mYEfOQ0Eh8v5yGe89Jj6qZuds=