language: python
python: "2.7"
install: true
script: true
deploy:
  provider: s3
  access_key_id: "AKIAJ43NJEFD3W7PPHFA"
  secret_access_key: 
    secure: "MqHd3GH19ckKx0g/kSt8G2awqVXRtNDtymet4OzeSiTgi94PNvOFE4Sp+8Vcksl843SWn4Am4j41cy1KrEZQ0EQ0easkuJZtVgjX5V5/vPokttM45Y0jQpdaUmM+Qxiilhw+oBRX+fcbBWOhh1+3Sd1fjzfzc/XeJO5aN7O7TpWyOr3i/aWDOQiuPGc/JeUvRl5IF+eJYecP4VyoD5JCXtDQ9Vv8Lhr+CjGGEZJNZY9ME16ScoLjEQjLuAwxCRgnv/z8JJ9ILb4Jcw/W+MNU95mSVr2Xg2I7oxNd7oDqa30DKjdzkku1rDHVTek8lmtueFwwMg9JhazExo89xnZavMxVEZMCMjPB9ihcVPAfllZgwC8tDJ5O2dU0CuzMkK6cv/8sZ0wPFwH3hZMqGc7vNiBwD2ZGXD08h7j4cOsetH7JzJIPOdUV4OJNNjLUoxyf3IW8GZ0t1eDRgzbEsiZSNtqq1OX7UsHjSPzCIcedtntvaVmv+LW7bspc8axLMH35azJ3sAnqi0C3Obn64KkFEf1jp4qoJ+5+R9VtMf0J05qm3w2AAiQkd2IcpFU0UFgrUV0rKgA9UQnYDzDg2GJCiP7Y6AMzH485KmiEYHON3bKI1qpq1ZkmyqzF7zvQlL/8EAQt7dhwGGrgzvVzP1SKcQ7YAw6Ks83d5T1+I1l4ab8="
  bucket: "thug-r.life"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: public