language: python
python: '2.7'
install: true
script: true
deploy:
  provider: s3
  access_key_id: AKIAJ43NJEFD3W7PPHFA
  secret_access_key: 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
  bucket: thug-r.life
  skip_cleanup: true
  region: us-east-1
  local_dir: public