language: python
python: '2.7'
install: true
script: true
deploy:
  provider: s3
  access_key_id: AKIAJ43NJEFD3W7PPHFA
  secret_access_key:
    secure: WU9iQpVi0oBS+iGarB1BWj7aIzk4f2fcQGNijnLRb+2YbC8kN5cAidsz2Q/fxCL0Yz4VpsQqyEeJ8elEhX2RbakeCu6XYB+CpGs9l0hRqzGQSI1P5kYEUzTwaJo4ayOsm0GJUUJVo7i83DecbnXoAu6h2IQzRbut0mMi3e9eMYlTzaHuIVLnwrfuCHZr4jLTaGohr3s1QesV6h5d5m4+fhoU7RlNiV7wiUGanKDUaHuirtY0+cL6US5UKYa9nu/Kobtcwes+eTo1yY50E3NsFNzhZ+AZC+7RQRji9nWesU14PLYVWJ1kTA3qCSI3vRBpDD+sdkppcLBSE8YGn+SlF5bincBi/opRBtJL58P0np9UmmyqdzNmpIISACtXDhmtAIiTIBUjyQ5udMfTsiSidefvaasHxsrf+eOlVTNN4gXp1ATvHPInHoc5axxvhskzHcHjNQo7RuvGjL982m3W/CldVl2Xjp/r+tsShM+/oWCyA5OYS2No2CIluQczt1FjKvuKlMjsz8AQD8/oGj0/UyKGFcyR1fDyYn6RLO4OodFi+C62rKJD13WybbH9y19QGiZjqmN9+ZsFtfd7qz/zVKJyfi6p8FgNt961xGpYISzIkc30umLlFMMzweama1ZfahB9gO9EVpd4oj8Z/ccFMumYAeIFez8Q7NambkE+AKU=
  bucket: thug-r.life
  skip_cleanup: true
  region: us-east-1
  local_dir: public