language: python
python: '2.7'
install: true
script: true
deploy:
  provider: s3
  access_key_id: AKIAJ43NJEFD3W7PPHFA
  secret_access_key:
    secure: vcodTr2LFrg0zuUPfGWvxZa6P2311ECgjawwZvjFlC8vExsgW5Otq2wErcUGULD99eMYp+7WM85vMwROJwmwPtYJzcBaIEUVYeWi+p3a4wK2ZwFOVMCGY8/50O0oNp7jAbugqhh/rFT08+RS2IUGm0qhT/4jXDAJoXhnpmE1/BVEmNuCg/0txFDnXDl9o17bXNr+O0LN+DWokcD49g7LPxsUv8HL/ar4hd+exe4a83+FhjcVNwq+7x1FAgd19lVp5Lni4gEtzuJ9H1iIGqL+eCrb05S5D7eCFIwx9VZEdrEO7w3Bc9aOg0j1exudqB/Z/Gw3NVqH6mnRDV4hnr2Usz+ov/N4CxIQxl8EQDMUhAE79MZMnZDjbvFakxDEMW0ZqKoRqvIY7S1aK6q4FCmTEPD4dTpNP82v9C4nOjWvPqVK7IFj6epS55N2vk+D5MEWUgU6Y0COJ10oaT7r56ZBHi9/Am5KxwdNcd+2L3iqXHv51wpfxiLUSF/TJmplpxnsVhgFGn3N1emgz4YlTYYtgQvkBx0f3TuJbZ7S1wVVwVVUGb65YUcHZLjV5z8A4KjAn1P2RcvFzcFGys/iNsdXRBJ4KP1+w20WYKMenZvcNlxm0ebO3RgLRL683NSpO06mnE0OoEcYihBRJ9ys/YlYSkLvaoEfLNuKWke2xYF5H+4=
  bucket: thug-r.life
  skip_cleanup: true
  region: us-east-1
  local_dir: public