language: python
python: '2.7'
install: true
script: true
deploy:
  provider: s3
  access_key_id: AKIAJ43NJEFD3W7PPHFA
  secret_access_key:
    secure: OFqUWBlaXK2iVW3t466aN6WHNqt0WQUXjuBOhjDlQqz/SUj8PqqDBBOw6QDseflZYAh/oYR52EFWJNMrIARiMyS5bUSICYSBw/uRD+mrFXU2mMK4lR/5Ue/D5ooNUrjroecXZRSvuIJIz7r0Ga2fIV3Yb0xlYVH2SYe4YspoZciJwf/ZGwV+3XbzJ5YfqAdFLL78p6zrEi90VvS1XIBplK3pV98BuE+LntquwETXSc+IEC6hEn+uItdwgB566I9dvbOHqFdsZJCUdj84p6GqjbRuwVUyyUQAPUPcWwAQcRdDkNbKuC7mo9zxEcrvspkryHwDoTTTBRuCHpwUNI9F5a9WSRemoNDYWtNFSC1OI8zUGw5YfOm7mXmJGr9tLMaPK4wL007dgPFDdrg14pflcasSSM8Mzdo53eVQArCVBBLtezb4CtA4ZeZYzQNAlSsQxgDSvmqBGM9za2D3RVhg09MHwvVRUKRQusE67AfU8u/6WFqYlwnuFnUnSPCTjnZoFI4wYcFyeacxhZ6oPbCSlVKa+E3j0L3Iz7Pqhxp30e2OcZz98bIlrERjgrTWK5m7+9/1pJXzupQfIKftBpQJILuAXQwZpr7Guof3MX6S/Qp8iHdGTK6A/cgjjQb5wtgg8ZMoDKNCmNUXG4MpJVajRmibQQ8MffGtN9bee9gpUUY=
  bucket: thug-r.life
  skip_cleanup: true
  region: us-east-1
  local_dir: public