baseurl = "http://thug-r.life/"
languageCode = "en-us"
title = "Thug R Life"
theme = "hugo-theme-terminal"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "thugrlife"
googleAnalytics = "UA-36686553-3"
math = true
ignoreFiles = ["\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    contentTypeName = "post"
    themeColor = "blue"
    showMenuItems = 3
    showLanguageSelector = false
    fullWidthTheme = false
    centerTheme = true
    # Sets the meta tag description, usually reserved for the main page
    description          = "Yet Another R Blog - but thuggish"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Thug R Life"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/post/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Thug R Life"

    paragraph = "Just a blog, by a guy trying to make a difference."

    about     = "I guess I'm starting this blog because I want to do more technical writing or something. Also, I've started publishing packages and so I need a platform to promote them on and starting a blog seems like a great way to get r-bloggers to publish my content. We'll see how it goes."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    imperfect = true
    width     = ""
    alt       = "Thug R Life"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 4

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Blog"
    url = "/post"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[langauges]
  [langagues.en]
    languageName = "English"
    title = "Thug-R Life"
    subtitle = "Just a blog, by a guy, trying to make a difference."
    
    [languages.en.params.logo]
      logoText = "Thug-R"

